### ISSUE TITLE
練習模式沒有退出功能

### ISSUE THREAD

**Issue by xuemeng1987** [konnokai/Rape-Senpai#1]
在練習模式中好像沒有什麽按鍵和按鈕可以退出練習模式呢
~~不過 比較好玩一點~~
希望以後難度可以加大一點 不然對一個osu!mania玩家來説應該是普通的2-3星的難度Map

**Comment by konnokai** [comment]
練習模式能跳的方式只有直接重整網頁，我主攻不是前端所以我也沒啥方式可以多個按鈕之類的來讓他跳回去
至於難度的部分，說真的畢竟這也不是純正音遊，全譜面採 RNG 方式產生也夠難打了，突然出一排縱連超難打
